### ISSUE TITLE
Directions wrapper

### ISSUE THREAD

**Issue by th3coop** [PaackEng/elm-google-maps#22]
I gave wrapping the directions webcomponent a shot today but it appears that the fact that it has the rendered `Map` as an attribute is a blocker for that.  Has anyone else tried to implement it?  I'm guess the answer is yes as the two main components that haven't been implemented are the ones that require a `Map` when it's instantiated.

Willing to give it a shot still if anyone has any pointers but I have a feeling this is a no go at this point.

**Comment by PedroHLC** [comment]
Sorry, we haven't gone far from the scope of what we already have implemented.

**Comment by th3coop** [comment]
Okie dokie.  Not sure I'll try to do this but regardless, this issue doesn't need to remain open.  Thanks for the response @PedroHLC .
